// Code generated by protoc-gen-idmsg. DO NOT EDIT.

package pb

import (
	"github.com/goodluck0107/gcore/glog"
	"github.com/goodluck0107/gcore/gprotocol/handler"
	"github.com/goodluck0107/gcore/gprotocol/interfaces"
	"google.golang.org/grpc"
)

func init() {
	handler.GetGRPCHandlersMgr().RegisterMsg(MsgDef)
	interfaces.AddRpcClientGenerator("Greeter", NewGreeterClient)
}

func NewGreeterClientDiscovery() (GreeterClient, error) {
	serviceName := "Greeter"
	target := "discovery://"+serviceName
	client, err := interfaces.GetRpcDiscoverer().NewMeshClient(target)
	if err!= nil {
		glog.Errorf("failed to discovery GreeterClient named: %s! err:%v", serviceName, err)
		return nil, err
	}
	return NewGreeterClient(client.Client().(grpc.ClientConnInterface)), nil
}

func AddGreeterServerProvider(svr GreeterServer) {
	serviceName := "Greeter"
	handler.GetGRPCHandlersMgr().RegisterServer(&Greeter_ServiceDesc, svr)
	interfaces.GetRpcProvider().AddServiceProvider(serviceName, &Greeter_ServiceDesc, svr)
}


