// Code generated by protoc-gen-idmsg. DO NOT EDIT.

package pb

import (
	"gitee.com/monobytes/gcore/glog"
	"gitee.com/monobytes/gcore/gprotocol/interfaces"
	"google.golang.org/grpc"
)

func init() {
	interfaces.AddRpcClient("Greeter", NewGreeterClient)
}

func NewDiscoveryGreeterClient() (GreeterClient, error) {
	serviceName := "Greeter"
	target := "discovery://"+serviceName
	client, err := interfaces.GetRpcProvider().NewMeshClient(target)
	if err!= nil {
		glog.Errorf("failed to discovery GreeterClient named: %s! err:%v", serviceName, err)
		return nil, err
	}
	return NewGreeterClient(client.Client().(grpc.ClientConnInterface)), nil
}

func AddGreeterServiceProvider(svr GreeterServer) {
	serviceName := "Greeter"
	interfaces.GetRpcProvider().AddServiceProvider(serviceName, &Greeter_ServiceDesc, svr)
}


