// Code generated by protoc-gen-idmsg. DO NOT EDIT.

package pb

import (
	"gitee.com/monobytes/gcore/gprotocol/interfaces"
	"google.golang.org/protobuf/proto"
)

var (
	MethodRouter = map[string]*interfaces.MethodItem{
		"/v1/greeter/hello": {HTTP: "GET", Method: "Greeter.Hello", Auth: 0, Cmd: int32(CMD_GreeterHello)},
	}

	IdMsg = map[int32]*interfaces.ReqItem{
		int32(CMD_GreeterHello): {Req: func() proto.Message { return &HelloReq{} }, Rsp: func() proto.Message { return &HelloRsp{} }, Auth: 0, Name: "/v1/greeter/hello", HTTP: "GET"},
    }
)
type MsgDefStruct struct{}

func (m *MsgDefStruct) GetMethodRouter() map[string]*interfaces.MethodItem {
	return MethodRouter
}
func (m *MsgDefStruct) GetIdMsg() map[int32]*interfaces.ReqItem {
	return IdMsg
}

var MsgDef = &MsgDefStruct{}