// Code generated by protoc-gen-idmsg. DO NOT EDIT.

let Protocol = {
  GreeterHello: "/v1/greeter/hello",
}

let ProtocolRouter 					= {} // 协议名:[code, req, rsp]
ProtocolRouter[Protocol.GreeterHello] = [1001, "HelloReq", "HelloRsp"]

let ProtocolId   = {} // 协议id: [router, req, rsp]
ProtocolId[1001] = [Protocol.GreeterHello, "HelloReq", "HelloRsp"]

export { Protocol, ProtocolRouter, ProtocolId }